runtime: python27
api_version: 1
threadsafe: true

runtime_config:
    python_version: 3

handlers:
- url: /.*
  script: app.app

skip_files:
- ^env$ #virtual environment's folder

libraries:
- name: ssl
  version: latest
